version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: finli-prometheus
    volumes:
      - ./prometheus-simple.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: finli-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"