global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'finli-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.251.70.130:8080']
        labels:
          application: 'FinLi Backend'
          environment: 'windows-local'
